### PR TITLE
Arguably, a few typographic improvement.

### PR DESCRIPTION
**Pull request by TApplencourt**
- Remove the use of italic and small caps on punctuation marks

Anyways, thank you for this great introduction!

### CODE REVIEW

**Comment by mrkline** [comment]
Hey, sorry for the delay, and thanks for taking the time to read it and offer suggestions!

At least in the typeface I'm using (Equity), punctuation set in small caps seems to look a touch better than the "full-sized" versions, especially when set in the middle of body text:

 sc

Regarding italicized punctuation,
itcomma
(The first comma is italicized, and the second is not.)

If there's any common style guidelines that disagree with these decisions, let me know - I'll readily admit that I might be making some wrong choices here.

**Comment by tavianator** [comment]
@mrkline Most style guides seem to advocate not italicizing the punctuation after an italic word or phrase (e.g. https://english.stackexchange.com/a/90775/62522)

**Comment by mrkline** [comment]
@tavianator Thanks for linking that! Looking through the project history, I think I ran into that same suggestion in December. See 9d71b403 - let me know if I missed a spot.

@TApplencourt  - I'd prefer to continue using the small caps parens. Besides those, are there other changes you'd like to make with this PR?

**Comment by TApplencourt** [comment]
@mrkline  No, and I was merely a suggestion. So I will close this PR . Thanks for this nice paper!

**Pull request closed without merging**
